# Config is set using Environment variable notation so that 
# the variables can be set as tokens and replaced with Environment variables
# during local dev
DB_NAME: "{{dbName}}"
DB_COLLECTION: "{{dbCollection}}"
DB_DOCUMENTS: "{{dbDocuments}}"
DB_USERNAME: "{{dbUserName}}"
DB_PASSWORD: "{{dbPassword}}"

#Not sure if there is a better way to get these values
ENVIRONMENT: "{{workingEnvironment}}"
CERTFILE_LOCATION: "{{certFile}}"
KEYFILE_LOCATION:  "{{keyFile}}"